### ISSUE TITLE
Add Necessary Files

### ISSUE THREAD

**Issue by ayato91** [gopavasanth/WhatsApp-Karo#3]
For the valid hacktober repository, it should contain CONTRIBUTING.MD file along with CODE_OF_CONDUCT.MD file.

**Comment by ayato91** [comment]
I can help you if you assign me to do so.

**Comment by gopavasanth** [comment]
@ayato91 please go a head, thanks for your interest :)

**Comment by gopavasanth** [comment]
As per https://github.com/gopavasanth/WhatsApp-Karo/pull/7
