### ISSUE TITLE
Implement Search in the country selection dropdown

### ISSUE THREAD

**Issue by gopavasanth** [gopavasanth/WhatsApp-Karo#5]
Currently, there is no search option in choosing countries, make this UI/UX nicer with a search ability with country name or code.

**Comment by gopavasanth** [comment]
<img width="468" alt="image" src="https://github.com/gopavasanth/WhatsApp-Karo/assets/30266744/8cf6969e-20ab-441e-bad5-1b945ae56454">

**Comment by Mrudul111** [comment]
Could you assign me this issue?

**Comment by M4dhav** [comment]
Could you please assign me this issue?

**Comment by gopavasanth** [comment]
Hey, Since @Mrudul111 requested it first, assigning it to you. Please feel free to un-assign if you plan to change your mind.

Expected design: 
![image](https://github.com/gopavasanth/WhatsApp-Karo/assets/30266744/76c70afc-f829-40c3-afaa-6610ea1bf8dd)

Thanks for your interest :)

**Comment by Mrudul111** [comment]
I have issued a PR please check it and let me know of any changes :)

**Comment by gopavasanth** [comment]
https://github.com/gopavasanth/WhatsApp-Karo/pull/8

Thank you for your contributions @Mrudul111  :)

**Comment by gopavasanth** [comment]
Done as per https://github.com/gopavasanth/WhatsApp-Karo/pull/8
